### ISSUE TITLE
Not compatible with react-native 75

### ISSUE THREAD

**Issue by ghost1face** [alexdonh/react-native-fast-base64#1]
As of ReactNative 75 it looks as though they've removed the `JSIModule*` types for Android:

https://reactnative.dev/blog/2024/08/12/release-0.75#android-jsimodule-has-been-deleted

It's a fairly new release so I'm not expecting this to already be caught up, but, are there any plans to use TurboModules?

**Comment by alexdonh** [comment]
> As of ReactNative 75 it looks as though they've removed the `JSIModule*` types for Android:
> 
> https://reactnative.dev/blog/2024/08/12/release-0.75#android-jsimodule-has-been-deleted
> 
> It's a fairly new release so I'm not expecting this to already be caught up, but, are there any plans to use TurboModules?

Thanks for the reminder. I'm well aware of JSIModule being set to deprecated and finally removed. The tricky part is.. I will have to make a Turbo Native Module to support RN 75+. Definitely one in my todos. But don't expect to see it anytime soon. Sorry :(
